services:
  postgres:
    image: postgres
    container_name: postgres-dotnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin1234!
      POSTGRES_DB: smjdb
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  smjregisterapi:
    build:
      context: .
      dockerfile: SMJRegisterAPI/Dockerfile
    depends_on:
      - postgres
    ports:
      # Maps host 8080 to container 80
      - "8080:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5000;Database=smjdb;Username=postgres;Password=Admin1234!
    restart: unless-stopped

volumes:
  postgres_data: