[build]
provider = "dotnet"
project = "SMJRegisterAPI/SMJRegisterAPI.csproj"
dotnet-version = "8.0.100"

[phases]
setup = [
  "dotnet restore SMJRegisterAPI/SMJRegisterAPI.csproj",
  "dotnet publish SMJRegisterAPI/SMJRegisterAPI.csproj -c Release -o /app"
]

[start]
cmd = "dotnet /app/SMJRegisterAPI.dll --urls http://0.0.0.0:$PORT"