// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMJRegisterAPI.Database.Contexts;

#nullable disable

namespace SMJRegisterAPI.Database.Migrations.ApplicationDbContextMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMJRegisterAPI.Entities.Camper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChurchId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Condicion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("Cedula");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Genero");

                    b.Property<int?>("GrantedCodeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGrant")
                        .HasColumnType("bit")
                        .HasColumnName("Becado");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int>("PaidAmount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadPaga");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ChurchId");

                    b.HasIndex("RoomId");

                    b.ToTable("Campistas", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ChurchId = 8,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 90, DateTimeKind.Utc).AddTicks(7161),
                            DocumentNumber = "63845666941",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Lara",
                            Name = "Marta",
                            PaidAmount = 668,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            ChurchId = 6,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 124, DateTimeKind.Utc).AddTicks(44),
                            DocumentNumber = "65538439745",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Ramírez",
                            Name = "Marta",
                            PaidAmount = 1034,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            ChurchId = 4,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 124, DateTimeKind.Utc).AddTicks(5120),
                            DocumentNumber = "14939194061",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Tejeda",
                            Name = "Laura",
                            PaidAmount = 1737,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            ChurchId = 2,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 124, DateTimeKind.Utc).AddTicks(7483),
                            DocumentNumber = "04818965650",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Malave",
                            Name = "Matilde",
                            PaidAmount = 1123,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            ChurchId = 2,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 124, DateTimeKind.Utc).AddTicks(9242),
                            DocumentNumber = "91493266936",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Puente",
                            Name = "Carles",
                            PaidAmount = 2467,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            ChurchId = 5,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(232),
                            DocumentNumber = "84299784109",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Lara",
                            Name = "Miguel",
                            PaidAmount = 1880,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            ChurchId = 10,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(1099),
                            DocumentNumber = "72124554813",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Vaca",
                            Name = "Marta",
                            PaidAmount = 1927,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            ChurchId = 7,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(2018),
                            DocumentNumber = "07035657764",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Arreola",
                            Name = "Matilde",
                            PaidAmount = 1412,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            ChurchId = 6,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(3383),
                            DocumentNumber = "31042579829",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Becerra",
                            Name = "Jennifer",
                            PaidAmount = 557,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            ChurchId = 6,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(5918),
                            DocumentNumber = "18090128161",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Reyna",
                            Name = "Lorena",
                            PaidAmount = 2190,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            ChurchId = 10,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(7064),
                            DocumentNumber = "00487995220",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Lebrón",
                            Name = "Ana",
                            PaidAmount = 1368,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            ChurchId = 9,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(8190),
                            DocumentNumber = "09729674760",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Marín",
                            Name = "Salvador",
                            PaidAmount = 1816,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            ChurchId = 10,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(9160),
                            DocumentNumber = "90871061860",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Arce",
                            Name = "Matilde",
                            PaidAmount = 993,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            ChurchId = 9,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 125, DateTimeKind.Utc).AddTicks(9899),
                            DocumentNumber = "22837623299",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Alemán",
                            Name = "Anni",
                            PaidAmount = 1588,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            ChurchId = 1,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(639),
                            DocumentNumber = "20263674605",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Montemayor",
                            Name = "Jennifer",
                            PaidAmount = 1890,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            ChurchId = 10,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(1684),
                            DocumentNumber = "74367686151",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Chavarría",
                            Name = "Anni",
                            PaidAmount = 710,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            ChurchId = 7,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(2414),
                            DocumentNumber = "64956938044",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Rangel",
                            Name = "Pedro",
                            PaidAmount = 677,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            ChurchId = 2,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(3042),
                            DocumentNumber = "11522817129",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Castillo",
                            Name = "Marta",
                            PaidAmount = 1939,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            ChurchId = 7,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(3675),
                            DocumentNumber = "11163318294",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Villa",
                            Name = "Ana",
                            PaidAmount = 727,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            ChurchId = 10,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(4502),
                            DocumentNumber = "34072381839",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Camacho",
                            Name = "Maica",
                            PaidAmount = 808,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21,
                            ChurchId = 6,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(5214),
                            DocumentNumber = "81881468242",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Sanabria",
                            Name = "Maica",
                            PaidAmount = 355,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22,
                            ChurchId = 7,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(6106),
                            DocumentNumber = "72892814180",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Véliz",
                            Name = "Laura",
                            PaidAmount = 2272,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23,
                            ChurchId = 10,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(6840),
                            DocumentNumber = "16173680771",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Meléndez",
                            Name = "Manuel",
                            PaidAmount = 211,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24,
                            ChurchId = 9,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(7684),
                            DocumentNumber = "80895072954",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Hidalgo",
                            Name = "Laura",
                            PaidAmount = 2162,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25,
                            ChurchId = 5,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(8254),
                            DocumentNumber = "98059197784",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Ocasio",
                            Name = "Pedro",
                            PaidAmount = 2131,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26,
                            ChurchId = 8,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(8938),
                            DocumentNumber = "56652584268",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Ibarra",
                            Name = "Daniel",
                            PaidAmount = 2067,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27,
                            ChurchId = 5,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 126, DateTimeKind.Utc).AddTicks(9771),
                            DocumentNumber = "12010232223",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Lucero",
                            Name = "Matilde",
                            PaidAmount = 1672,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28,
                            ChurchId = 2,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(913),
                            DocumentNumber = "56972295906",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "de Anda",
                            Name = "Sergi",
                            PaidAmount = 93,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29,
                            ChurchId = 3,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(1721),
                            DocumentNumber = "05321197296",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Henríquez",
                            Name = "Anni",
                            PaidAmount = 2296,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30,
                            ChurchId = 4,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(2497),
                            DocumentNumber = "45269053988",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Nava",
                            Name = "Daniel",
                            PaidAmount = 169,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31,
                            ChurchId = 5,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(3224),
                            DocumentNumber = "14152096872",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Moya",
                            Name = "Matilde",
                            PaidAmount = 1014,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32,
                            ChurchId = 6,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(3779),
                            DocumentNumber = "74013806299",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Urías",
                            Name = "Jorge",
                            PaidAmount = 1265,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33,
                            ChurchId = 3,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(4789),
                            DocumentNumber = "61361217062",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Linares",
                            Name = "Laura",
                            PaidAmount = 578,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34,
                            ChurchId = 2,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(5519),
                            DocumentNumber = "17604286802",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Guerrero",
                            Name = "Andrea",
                            PaidAmount = 2394,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35,
                            ChurchId = 10,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(6396),
                            DocumentNumber = "75111388499",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Ybarra",
                            Name = "Roser",
                            PaidAmount = 1199,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36,
                            ChurchId = 10,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(7035),
                            DocumentNumber = "44603425854",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Jiménez",
                            Name = "Josep",
                            PaidAmount = 978,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37,
                            ChurchId = 6,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(7788),
                            DocumentNumber = "82005573183",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Gallegos",
                            Name = "Manuel",
                            PaidAmount = 986,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38,
                            ChurchId = 3,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(8638),
                            DocumentNumber = "86323751619",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Atencio",
                            Name = "Salvador",
                            PaidAmount = 1485,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39,
                            ChurchId = 6,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 127, DateTimeKind.Utc).AddTicks(9591),
                            DocumentNumber = "37151829926",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Chapa",
                            Name = "Ángel",
                            PaidAmount = 1554,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40,
                            ChurchId = 9,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(416),
                            DocumentNumber = "84283568810",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Rincón",
                            Name = "Miguel",
                            PaidAmount = 641,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 41,
                            ChurchId = 7,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(1205),
                            DocumentNumber = "94412281228",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Alejandro",
                            Name = "Salvador",
                            PaidAmount = 263,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 42,
                            ChurchId = 2,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(2055),
                            DocumentNumber = "07147995953",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Linares",
                            Name = "Salvador",
                            PaidAmount = 1296,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 43,
                            ChurchId = 5,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(2842),
                            DocumentNumber = "82242620696",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Tovar",
                            Name = "Jennifer",
                            PaidAmount = 451,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 44,
                            ChurchId = 6,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(3706),
                            DocumentNumber = "52212091124",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Quintanilla",
                            Name = "Anni",
                            PaidAmount = 454,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 45,
                            ChurchId = 3,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(4436),
                            DocumentNumber = "82943022279",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Ortega",
                            Name = "Maica",
                            PaidAmount = 1691,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 46,
                            ChurchId = 5,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(5157),
                            DocumentNumber = "95774955525",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Orosco",
                            Name = "Carles",
                            PaidAmount = 1357,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 47,
                            ChurchId = 3,
                            Condition = "Executive",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(5811),
                            DocumentNumber = "20508809920",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Pérez",
                            Name = "Marta",
                            PaidAmount = 1668,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 48,
                            ChurchId = 5,
                            Condition = "RegularCamper",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(6738),
                            DocumentNumber = "78852040778",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Espinal",
                            Name = "Andrea",
                            PaidAmount = 1390,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 49,
                            ChurchId = 4,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(7733),
                            DocumentNumber = "54181759727",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Vélez",
                            Name = "Carles",
                            PaidAmount = 875,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 50,
                            ChurchId = 9,
                            Condition = "Staff",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 128, DateTimeKind.Utc).AddTicks(8852),
                            DocumentNumber = "81609485696",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            IsPaid = false,
                            LastName = "Flórez",
                            Name = "Lorena",
                            PaidAmount = 681,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Church", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Conferencia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PrimerNombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Iglesias", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Conference = "Southeast",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 75, DateTimeKind.Utc).AddTicks(387),
                            IsDeleted = false,
                            Name = "Zaragoza",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            Conference = "Northeast",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(4497),
                            IsDeleted = false,
                            Name = "Santander",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            Conference = "Northeast",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(5546),
                            IsDeleted = false,
                            Name = "El Ejido",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            Conference = "Southeast",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(5603),
                            IsDeleted = false,
                            Name = "Castellón de la Plana",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            Conference = "Central",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(5664),
                            IsDeleted = false,
                            Name = "Santander",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            Conference = "Northeast",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(5693),
                            IsDeleted = false,
                            Name = "Vitoria",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            Conference = "Central",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(5720),
                            IsDeleted = false,
                            Name = "Vigo",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            Conference = "Central",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(5744),
                            IsDeleted = false,
                            Name = "Sanlúcar de Barrameda",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            Conference = "Southeast",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(5778),
                            IsDeleted = false,
                            Name = "Alcorcón",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            Conference = "Northeast",
                            CreatedAt = new DateTime(2025, 7, 15, 5, 29, 15, 86, DateTimeKind.Utc).AddTicks(5801),
                            IsDeleted = false,
                            Name = "Leganés",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.GrantedCode", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("CamperId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrantAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("CodigosDeDescuento", (string)null);
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("CapacidadMaxima");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombreHabitacion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Habitaciones", (string)null);
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Camper", b =>
                {
                    b.HasOne("SMJRegisterAPI.Entities.Church", "Church")
                        .WithMany("Campers")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMJRegisterAPI.Entities.Room", "Room")
                        .WithMany("Campers")
                        .HasForeignKey("RoomId");

                    b.Navigation("Church");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.GrantedCode", b =>
                {
                    b.HasOne("SMJRegisterAPI.Entities.Camper", "Camper")
                        .WithOne("GrantedCode")
                        .HasForeignKey("SMJRegisterAPI.Entities.GrantedCode", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Camper", b =>
                {
                    b.Navigation("GrantedCode")
                        .IsRequired();
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Church", b =>
                {
                    b.Navigation("Campers");
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Room", b =>
                {
                    b.Navigation("Campers");
                });
#pragma warning restore 612, 618
        }
    }
}
