// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMJRegisterAPI.Database.Contexts;

#nullable disable

namespace SMJRegisterAPI.Database.Migrations.ApplicationDbContextMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMJRegisterAPI.Entities.Camper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChurchId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Condicion");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Genero");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGrant")
                        .HasColumnType("bit")
                        .HasColumnName("Becado");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int>("PaidAmount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadPaga");

                    b.HasKey("ID");

                    b.HasIndex("ChurchId");

                    b.ToTable("Campistas", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ChurchId = 7,
                            Condition = "RegularCamper",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Zepeda",
                            Name = "Sergi",
                            PaidAmount = 1084
                        },
                        new
                        {
                            ID = 2,
                            ChurchId = 2,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Hernández",
                            Name = "Ana",
                            PaidAmount = 1138
                        },
                        new
                        {
                            ID = 3,
                            ChurchId = 7,
                            Condition = "Executive",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Lugo",
                            Name = "Marta",
                            PaidAmount = 905
                        },
                        new
                        {
                            ID = 4,
                            ChurchId = 3,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Cadena",
                            Name = "Laura",
                            PaidAmount = 1503
                        },
                        new
                        {
                            ID = 5,
                            ChurchId = 7,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Garrido",
                            Name = "Manuel",
                            PaidAmount = 242
                        },
                        new
                        {
                            ID = 6,
                            ChurchId = 7,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Padrón",
                            Name = "Rubén",
                            PaidAmount = 37
                        },
                        new
                        {
                            ID = 7,
                            ChurchId = 8,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Guardado",
                            Name = "Rubén",
                            PaidAmount = 1720
                        },
                        new
                        {
                            ID = 8,
                            ChurchId = 7,
                            Condition = "RegularCamper",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Aragón",
                            Name = "Lorena",
                            PaidAmount = 480
                        },
                        new
                        {
                            ID = 9,
                            ChurchId = 1,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Barrientos",
                            Name = "Sergi",
                            PaidAmount = 2181
                        },
                        new
                        {
                            ID = 10,
                            ChurchId = 2,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Villegas",
                            Name = "Roser",
                            PaidAmount = 1550
                        },
                        new
                        {
                            ID = 11,
                            ChurchId = 6,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Gallegos",
                            Name = "Laura",
                            PaidAmount = 387
                        },
                        new
                        {
                            ID = 12,
                            ChurchId = 9,
                            Condition = "Staff",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Valentín",
                            Name = "Jennifer",
                            PaidAmount = 1344
                        },
                        new
                        {
                            ID = 13,
                            ChurchId = 4,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Medina",
                            Name = "Daniel",
                            PaidAmount = 1461
                        },
                        new
                        {
                            ID = 14,
                            ChurchId = 4,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Carrero",
                            Name = "Matilde",
                            PaidAmount = 77
                        },
                        new
                        {
                            ID = 15,
                            ChurchId = 8,
                            Condition = "RegularCamper",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Vigil",
                            Name = "Maica",
                            PaidAmount = 1509
                        },
                        new
                        {
                            ID = 16,
                            ChurchId = 5,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Urbina",
                            Name = "Marta",
                            PaidAmount = 1992
                        },
                        new
                        {
                            ID = 17,
                            ChurchId = 8,
                            Condition = "Executive",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Ocampo",
                            Name = "Laura",
                            PaidAmount = 354
                        },
                        new
                        {
                            ID = 18,
                            ChurchId = 6,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Olivárez",
                            Name = "Pedro",
                            PaidAmount = 1562
                        },
                        new
                        {
                            ID = 19,
                            ChurchId = 3,
                            Condition = "Executive",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Urrutia",
                            Name = "Daniel",
                            PaidAmount = 177
                        },
                        new
                        {
                            ID = 20,
                            ChurchId = 6,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Becerra",
                            Name = "Manuel",
                            PaidAmount = 170
                        },
                        new
                        {
                            ID = 21,
                            ChurchId = 1,
                            Condition = "Executive",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Bernal",
                            Name = "Roser",
                            PaidAmount = 1690
                        },
                        new
                        {
                            ID = 22,
                            ChurchId = 6,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Mireles",
                            Name = "Andrea",
                            PaidAmount = 1452
                        },
                        new
                        {
                            ID = 23,
                            ChurchId = 2,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Araña",
                            Name = "Jennifer",
                            PaidAmount = 1893
                        },
                        new
                        {
                            ID = 24,
                            ChurchId = 6,
                            Condition = "RegularCamper",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Casillas",
                            Name = "Matilde",
                            PaidAmount = 212
                        },
                        new
                        {
                            ID = 25,
                            ChurchId = 2,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Meza",
                            Name = "Roser",
                            PaidAmount = 176
                        },
                        new
                        {
                            ID = 26,
                            ChurchId = 8,
                            Condition = "RegularCamper",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Aragón",
                            Name = "Lorena",
                            PaidAmount = 2345
                        },
                        new
                        {
                            ID = 27,
                            ChurchId = 4,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Irizarry",
                            Name = "Jordi",
                            PaidAmount = 798
                        },
                        new
                        {
                            ID = 28,
                            ChurchId = 8,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Luna",
                            Name = "Josep",
                            PaidAmount = 2104
                        },
                        new
                        {
                            ID = 29,
                            ChurchId = 3,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Caballero",
                            Name = "Ana",
                            PaidAmount = 1241
                        },
                        new
                        {
                            ID = 30,
                            ChurchId = 4,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Pulido",
                            Name = "Matilde",
                            PaidAmount = 1085
                        },
                        new
                        {
                            ID = 31,
                            ChurchId = 8,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Nieto",
                            Name = "Pedro",
                            PaidAmount = 2267
                        },
                        new
                        {
                            ID = 32,
                            ChurchId = 2,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Álvarez",
                            Name = "Carles",
                            PaidAmount = 2197
                        },
                        new
                        {
                            ID = 33,
                            ChurchId = 2,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Delao",
                            Name = "Josep",
                            PaidAmount = 1579
                        },
                        new
                        {
                            ID = 34,
                            ChurchId = 1,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Delgadillo",
                            Name = "Daniel",
                            PaidAmount = 967
                        },
                        new
                        {
                            ID = 35,
                            ChurchId = 4,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Mayorga",
                            Name = "Rubén",
                            PaidAmount = 349
                        },
                        new
                        {
                            ID = 36,
                            ChurchId = 1,
                            Condition = "Executive",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Salcedo",
                            Name = "Maica",
                            PaidAmount = 511
                        },
                        new
                        {
                            ID = 37,
                            ChurchId = 1,
                            Condition = "Staff",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Mireles",
                            Name = "Sergi",
                            PaidAmount = 1640
                        },
                        new
                        {
                            ID = 38,
                            ChurchId = 6,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Palacios",
                            Name = "Andrea",
                            PaidAmount = 2015
                        },
                        new
                        {
                            ID = 39,
                            ChurchId = 3,
                            Condition = "Staff",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Rolón",
                            Name = "Andrea",
                            PaidAmount = 2475
                        },
                        new
                        {
                            ID = 40,
                            ChurchId = 4,
                            Condition = "Staff",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Miranda",
                            Name = "Matilde",
                            PaidAmount = 2331
                        },
                        new
                        {
                            ID = 41,
                            ChurchId = 4,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Mascareñas",
                            Name = "Iván",
                            PaidAmount = 2033
                        },
                        new
                        {
                            ID = 42,
                            ChurchId = 7,
                            Condition = "RegularCamper",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Tejada",
                            Name = "Carles",
                            PaidAmount = 2294
                        },
                        new
                        {
                            ID = 43,
                            ChurchId = 8,
                            Condition = "Executive",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Roque",
                            Name = "Salvador",
                            PaidAmount = 996
                        },
                        new
                        {
                            ID = 44,
                            ChurchId = 6,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Madera",
                            Name = "Laura",
                            PaidAmount = 97
                        },
                        new
                        {
                            ID = 45,
                            ChurchId = 4,
                            Condition = "Executive",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Castellanos",
                            Name = "Laura",
                            PaidAmount = 1911
                        },
                        new
                        {
                            ID = 46,
                            ChurchId = 5,
                            Condition = "RegularCamper",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Guardado",
                            Name = "Roser",
                            PaidAmount = 395
                        },
                        new
                        {
                            ID = 47,
                            ChurchId = 6,
                            Condition = "RegularCamper",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Pedroza",
                            Name = "Matilde",
                            PaidAmount = 1637
                        },
                        new
                        {
                            ID = 48,
                            ChurchId = 3,
                            Condition = "Staff",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Bañuelos",
                            Name = "Daniel",
                            PaidAmount = 1098
                        },
                        new
                        {
                            ID = 49,
                            ChurchId = 10,
                            Condition = "Executive",
                            Gender = "Female",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Muro",
                            Name = "Ana",
                            PaidAmount = 354
                        },
                        new
                        {
                            ID = 50,
                            ChurchId = 6,
                            Condition = "RegularCamper",
                            Gender = "Male",
                            IsDeleted = false,
                            IsGrant = false,
                            LastName = "Zúñiga",
                            Name = "Iván",
                            PaidAmount = 2105
                        });
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Church", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Conferencia");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PrimerNombre");

                    b.HasKey("ID");

                    b.ToTable("Iglesias", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Conference = "Central",
                            IsDeleted = false,
                            Name = "Valdemoro"
                        },
                        new
                        {
                            ID = 2,
                            Conference = "Northeast",
                            IsDeleted = false,
                            Name = "Barcelona"
                        },
                        new
                        {
                            ID = 3,
                            Conference = "Central",
                            IsDeleted = false,
                            Name = "Pamplona"
                        },
                        new
                        {
                            ID = 4,
                            Conference = "Central",
                            IsDeleted = false,
                            Name = "Viladecans"
                        },
                        new
                        {
                            ID = 5,
                            Conference = "Northeast",
                            IsDeleted = false,
                            Name = "Badalona"
                        },
                        new
                        {
                            ID = 6,
                            Conference = "Southeast",
                            IsDeleted = false,
                            Name = "Inca"
                        },
                        new
                        {
                            ID = 7,
                            Conference = "Central",
                            IsDeleted = false,
                            Name = "Alcalá de Henares"
                        },
                        new
                        {
                            ID = 8,
                            Conference = "Northeast",
                            IsDeleted = false,
                            Name = "Torremolinos"
                        },
                        new
                        {
                            ID = 9,
                            Conference = "Central",
                            IsDeleted = false,
                            Name = "Badalona"
                        },
                        new
                        {
                            ID = 10,
                            Conference = "Southeast",
                            IsDeleted = false,
                            Name = "Vigo"
                        });
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Camper", b =>
                {
                    b.HasOne("SMJRegisterAPI.Entities.Church", "Church")
                        .WithMany("Campers")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("SMJRegisterAPI.Entities.Church", b =>
                {
                    b.Navigation("Campers");
                });
#pragma warning restore 612, 618
        }
    }
}
